<div class="modal fade in" id="comment_report_box" role="dialog">
    <div class="modal-dialog">
    
      <div class="modal-content">
        <p style="text-align: center;padding: 30px 20px;font-family: Hind,Arial;font-size: 16px;">
          <i class="fa fa-check" aria-hidden="true" style="color: green;"></i>      
          <span class="msg"><?php echo $wo['lang']['comment_reported']; ?></span>
        </p>
      </div>
      
    </div>
</div>

<div class="modal fade in" id="post-shared" role="dialog">
    <div class="modal-dialog">
    
      <div class="modal-content">
        <p style="text-align: center;padding: 30px 20px;font-family: Hind,Arial;font-size: 16px;">
          <i class="fa fa-check" aria-hidden="true" style="color: green;"></i>      
          <?php echo $wo['lang']['post_shared']; ?>
        </p>
      </div>
      
    </div>
</div>
<div class="modal fade in" id="modal-alert" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <p style="text-align: center;padding: 30px 20px;font-family: Hind,Arial;font-size: 16px;">
          <i class="fa fa-info-circle" aria-hidden="true" style="color: #31708f;"></i>      
          <span id="modal-alert-msg">
            <?php 
              $limit = $wo['config']['connectivitySystemLimit'];
              $text  = preg_replace("/\{\{CNTC_LIMIT\}\}/", $limit, $wo['lang']['cntc_limit_reached']);
              echo $text;
            ?>
          </span>
        </p>
      </div>
    </div>
</div>
<div class="modal fade in" id="invalid_file" role="dialog">
    <div class="modal-dialog">
    
      <div class="modal-content">
        <p style="text-align: center;padding: 30px 20px;font-family: Hind,Arial;font-size: 14px;">
          <i class="fa fa-info-circle main" aria-hidden="true" style="color:#f2dede;"></i>      
          <?php echo str_replace('{file_size}', Wo_SizeUnits($wo['config']['maxUpload']), $wo['lang']['file_too_big']); ?>
        </p>
      </div>
      
    </div>
</div>
<div class="modal fade in" id="file_not_supported" role="dialog">
    <div class="modal-dialog">
    
      <div class="modal-content">
        <p style="text-align: center;padding: 30px 20px;font-family: Hind,Arial;font-size: 14px;">
          <i class="fa fa-info-circle main" aria-hidden="true" style="color:#f2dede;"></i>      
          <?php echo $wo['lang']['file_not_supported']; ?>
        </p>
      </div>
      
    </div>
</div>
<div class="modal fade" id="modal_light_box" role="dialog">
	<button type="button" class="close comm_mod_img_close" data-dismiss="modal" aria-label="Close"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></button>
  <div class="modal-dialog" >
    <div class="modal-content">              
      <div class="modal-body" style="padding: 0;">
        <img  class="image" style="width: 100%;" >
      </div>
    </div>
  </div>
</div>
<div class="modal fade in" id="adult_image_file" role="dialog">
    <div class="modal-dialog">
    
      <div class="modal-content">
        <p style="text-align: center;padding: 30px 20px;font-family: Hind,Arial;font-size: 14px;">
          <i class="fa fa-info-circle main" aria-hidden="true" style="color:#f2dede;"></i>      
          <?php echo $wo['lang']['adult_image_file']; ?>
        </p>
      </div>
      
    </div>
</div>
<div class="modal fade" id="share_post_on_group" role="dialog">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
        <h4 class="modal-title">
          <?php  echo $wo['lang']['share_post_on_group']; ?>
        </h4>
      </div>
      <form id="share_post_on_group_form" class="share_post_on_group_form" method="POST">
        <div class="modal-body">
          <div id="share_post_on_group_form_alert"></div>
          <div class="form-group input-group">
            <span class="input-group-addon pointer">
              <svg xmlns="http://www.w3.org/2000/svg" class="feather" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color:#03A9F4;"><rect x="3" y="3" width="7" height="7"></rect><rect x="14" y="3" width="7" height="7"></rect><rect x="14" y="14" width="7" height="7"></rect><rect x="3" y="14" width="7" height="7"></rect></svg>
            </span>
            <input onkeydown="SearchFor(this,'group')" type="text" class="form-control" name="name" placeholder="<?php echo $wo['lang']['please_group_name']; ?>">
            <input type="hidden" id="SearchForInputGroup" name="group_id">
            <input type="hidden" id="SearchForInputPostId" name="post_id">
          </div>
        </div>
        <div class="modal-footer">
          <div class="ball-pulse"><div></div><div></div><div></div></div>
          <button id="share_post_on_group_form_btn" type="button" class="btn btn-main">
            <?php echo $wo['lang']['share']; ?>
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
<div class="modal fade" id="share_post_on_page" role="dialog">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
        <h4 class="modal-title">
          <?php  echo $wo['lang']['share_post_on_page']; ?>
        </h4>
      </div>
      <form id="share_post_on_page_form" class="share_post_on_page_form" method="POST">
        <div class="modal-body">
          <div id="share_post_on_page_form_alert"></div>
          <div class="form-group input-group">
            <span class="input-group-addon pointer">
              <svg xmlns="http://www.w3.org/2000/svg" class="feather" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="color:#f79f58;"><path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z"></path><line x1="4" y1="22" x2="4" y2="15"></line></svg>
            </span>
            <input onkeydown="SearchFor(this,'page')" type="text" class="form-control" name="name" placeholder="<?php echo $wo['lang']['please_page_name']; ?>">
            <input type="hidden" id="SearchForInputPage" name="page_id">
            <input type="hidden" id="SearchForInputPostIdPage" name="post_id">
          </div>
        </div>
        <div class="modal-footer">
          <div class="ball-pulse"><div></div><div></div><div></div></div>
          <button id="share_post_on_page_form_btn" type="button" class="btn btn-main">
            <?php echo $wo['lang']['share']; ?>
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
<div class="modal fade" id="share_post_on_user" role="dialog">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
        <h4 class="modal-title">
          <?php  echo $wo['lang']['share_post_on_user']; ?>
        </h4>
      </div>
      <form id="share_post_on_page_form" class="share_post_on_user_form" method="POST">
        <div class="modal-body">
          <div id="share_post_on_user_form_alert"></div>
          <div class="form-group input-group">
            <span class="input-group-addon pointer">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-share" style="margin-top: -4px;width: 19px;height: 19px;"><path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"></path><polyline points="16 6 12 2 8 6"></polyline><line x1="12" y1="2" x2="12" y2="15"></line></svg>
            </span>
            <input onkeydown="SearchFor(this,'user')" type="text" class="form-control" name="name" placeholder="<?php echo $wo['lang']['username']; ?>">
            <input type="hidden" id="SearchForInputUser" name="user_id">
            <input type="hidden" id="SearchForInputUserPostId" name="post_id">
          </div>
        </div>
        <div class="modal-footer">
          <div class="ball-pulse"><div></div><div></div><div></div></div>
          <button id="share_post_on_user_form_btn" type="button" class="btn btn-main">
            <?php echo $wo['lang']['share']; ?>
          </button>
        </div>
      </form>
    </div>
  </div>
</div>


<div class="modal fade sun_modal" id="views-info-modal" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><span id="views_info_title"></span></h4>
			</div>
			<div class="modal-body">
				<div id="views_info" class="wo_react_ursrs_list"></div>
				<div class="clearfix"></div>
				<div id="views_info_load" style="display: none;">
					<div class="load-more views_info_load_ wo_react_ursrs_list_lod_mor">
						<button class="btn btn-default text-center views_info_load_more" data-type="" post-id="" table-type="" onclick="Wo_LoadViewsInfo(this);"><span id="load_more_info_btn"><?php echo $wo['lang']['load_more'] ?></span>
						</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="modal fade sun_modal" id="users-reacted-modal" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title">
					<div class="who_react_modal">

            <?php if (!empty($wo['reactions_types'])) {
                foreach ($wo['reactions_types'] as $key => $value) {
                  if ($value['status'] == 1) {
                    
                 ?>
                 <span class="how_reacted like-btn-like pointer" id="_post333" onclick="Wo_LoadReactedUsers(<?php echo $key; ?>);">
                <?php if (preg_match("/<[^<]+>/",$value['wowonder_icon'],$m)) {
                      if ($key == 1) { ?>
                        <div class="inline_post_emoji inline_act_emoji no_anim"><div class="emoji emoji--like"><div class="emoji__hand"><div class="emoji__thumb"></div></div></div></div>
                     <?php  }elseif ($key == 2) { ?>
                        <div class="inline_post_emoji inline_act_emoji no_anim"><div class="emoji emoji--love"><div class="emoji__heart"></div></div></div>
                    <?php  }elseif ($key == 3) { ?>
                      <div class="inline_post_emoji inline_act_emoji no_anim"><div class="emoji emoji--haha"><div class="emoji__face"><div class="emoji__eyes"></div><div class="emoji__mouth"><div class="emoji__tongue"></div></div></div></div></div>
                    <?php }elseif ($key == 4) { ?>
                      <div class="inline_post_emoji inline_act_emoji no_anim"><div class="emoji emoji--wow"><div class="emoji__face"><div class="emoji__eyebrows"></div><div class="emoji__eyes"></div><div class="emoji__mouth"></div></div></div></div>
                    <?php }elseif ($key == 5) { ?>
                      <div class="inline_post_emoji inline_act_emoji no_anim"><div class="emoji emoji--sad"><div class="emoji__face"><div class="emoji__eyebrows"></div><div class="emoji__eyes"></div><div class="emoji__mouth"></div></div></div></div>
                    <?php }elseif ($key == 6) { ?>
                      <div class="inline_post_emoji inline_act_emoji no_anim"><div class="emoji emoji--angry"><div class="emoji__face"><div class="emoji__eyebrows"></div><div class="emoji__eyes"></div><div class="emoji__mouth"></div></div></div></div>
                    <?php }
                   }
                   else{ ?>
                    <div class="inline_post_emoji no_anim"><div class="reaction"><img src="<?php echo($value['wowonder_icon']) ?>"></div></div>
                  <?php } ?>
                </span>
            <?php } } } ?>


						<!-- <span class="how_reacted like-btn-like pointer" id="_post333" onclick="Wo_LoadReactedUsers('like');">
							<div class="inline_post_emoji inline_act_emoji no_anim"><div class="emoji emoji--like"><div class="emoji__hand"><div class="emoji__thumb"></div></div></div></div>
						</span>
						<span class="how_reacted like-btn-love pointer" id="_post333" onclick="Wo_LoadReactedUsers('love');">
							<div class="inline_post_emoji inline_act_emoji no_anim"><div class="emoji emoji--love"><div class="emoji__heart"></div></div></div>
						</span>
						<span class="how_reacted like-btn-haha pointer" id="_post333" onclick="Wo_LoadReactedUsers('haha');">
							<div class="inline_post_emoji inline_act_emoji no_anim"><div class="emoji emoji--haha"><div class="emoji__face"><div class="emoji__eyes"></div><div class="emoji__mouth"><div class="emoji__tongue"></div></div></div></div></div>
						</span>
						<span class="how_reacted like-btn-wow pointer" id="_post333" onclick="Wo_LoadReactedUsers('wow');">
							<div class="inline_post_emoji inline_act_emoji no_anim"><div class="emoji emoji--wow"><div class="emoji__face"><div class="emoji__eyebrows"></div><div class="emoji__eyes"></div><div class="emoji__mouth"></div></div></div></div>
						</span>
						<span class="how_reacted like-btn-sad pointer" id="_post333" onclick="Wo_LoadReactedUsers('sad');">
							<div class="inline_post_emoji inline_act_emoji no_anim"><div class="emoji emoji--sad"><div class="emoji__face"><div class="emoji__eyebrows"></div><div class="emoji__eyes"></div><div class="emoji__mouth"></div></div></div></div>
						</span>
						<span class="how_reacted like-btn-angry pointer" id="_post333" onclick="Wo_LoadReactedUsers('angry');">
							<div class="inline_post_emoji inline_act_emoji no_anim"><div class="emoji emoji--angry"><div class="emoji__face"><div class="emoji__eyebrows"></div><div class="emoji__eyes"></div><div class="emoji__mouth"></div></div></div></div>
						</span> -->
					</div>
				</h4>
			</div>
			<div class="modal-body">
				<div id="reacted_users_box" class="wo_react_ursrs_list"></div>
				<div class="clearfix"></div>
				<div id="reacted_users_load" style="display: none;">
					<div class="load-more wo_react_ursrs_list_lod_mor">
						<button class="btn btn-default text-center reacted_users_load_more" data-type="" post-id="" col-type="" onclick="Wo_LoadMoreReactedUsers(this);"><span id="load_more_reacted_btn"><?php echo $wo['lang']['load_more'] ?></span>
						</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<div class="modal fade in" id="approve_post" role="dialog">
	<div class="modal-dialog wow_mat_mdl">
		<div class="modal-content">
			<div class="empty_state" style="margin: 40px 0;"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M9,13A3,3 0 0,0 12,16A3,3 0 0,0 15,13A3,3 0 0,0 12,10A3,3 0 0,0 9,13M20,19.59V8L14,2H6A2,2 0 0,0 4,4V20A2,2 0 0,0 6,22H18C18.45,22 18.85,21.85 19.19,21.6L14.76,17.17C13.96,17.69 13,18 12,18A5,5 0 0,1 7,13A5,5 0 0,1 12,8A5,5 0 0,1 17,13C17,14 16.69,14.96 16.17,15.75L20,19.59Z" /></svg> <?php echo $wo['lang']['approve_post_text']; ?></div>
		</div>
	</div>
</div>

<div class="modal fade in" id="error_post" role="dialog">
    <div class="modal-dialog">
    
      <div class="modal-content">
        <p style="text-align: center;padding: 30px 20px;font-family: Hind,Arial;font-size: 14px;" id="error_post_text">
        </p>
      </div>
      
    </div>
</div>

<div class="modal fade in" id="pro_upload_file" role="dialog">
    <div class="modal-dialog">
    
      <div class="modal-content">
        <p style="text-align: center;padding: 30px 20px;font-family: Hind,Arial;font-size: 14px;">
          <i class="fa fa-info-circle main" aria-hidden="true" style="color:#f2dede;"></i>      
          <?php echo $wo['lang']['free_plan_upload']; ?> <a href="<?php echo Wo_SeoLink('index.php?link1=go-pro'); ?>"><?php echo $wo['lang']['upgrade_to_pro']; ?></a>
        </p>
      </div>
      
    </div>
</div>

<div class="modal fade sun_modal" id="edit-offer-modal" role="dialog">
<div class="modal-dialog">
      <div class="modal-content">
            <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
                  <h4 class="modal-title"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg> <?php echo $wo['lang']['edit_offer'] ?></h4>
            </div>
            <div class="modal-body">
                  <div class="wo_settings_page">
                        <form class="edit-offer-form form-horizontal" method="post">
                              <div class="app-offer-alert app-general-alert"></div>
                              <div class="clear"></div>
                              <div class="setting-panel row job-setting-panel edit_offer_modal_form">
                                    

                              </div>

                              <div class="publisher-hidden-option">
                                    <div id="progress" class="create-offer-progress">
                                          <span id="percent" class="create-product-percent <?php echo Wo_RightToLeft('pull-right');?>">0%</span>
                                          <div class="progress">
                                                <div id="bar" class="progress-bar active create-product-bar"></div> 
                                          </div>
                                          <div class="clear"></div>
                                    </div>
                              </div>

                              
                              <div class="form-group last-sett-btn modal-footer">
                                    <div class="ball-pulse"><div></div><div></div><div></div></div>
                                    <button type="submit" class="btn btn-main setting-panel-mdbtn"><?php echo $wo['lang']['publish'] ?></button>
                              </div>
                        </form>
                  </div>
            </div>
      </div>
</div>
</div>