<div class="container-fluid">
    <div>
        <h3>Auto Group Join</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Tools</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Auto Group Join</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Auto Group Join</h6>
                    <div class="alert alert-info">When a user creates a new account, choose which group you would like to get auto join.</div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">group name(s), sperated by a comma (,)</label>
                                <input type="text" id="users" name="users" class="form-control" value="<?php echo $wo['config']['auto_group_join']; ?>">
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <small>This process might take some time, you can check for your site changes after few minutes.</small>
                        <div class="clearfix"></div>
                        <br>
                  <button type="submit" class="btn btn-danger waves-effect waves-light m-t-20" id="users-btn">Save</button>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    </div>
<script>
$(document).on('click', '#users-btn', function(event) {
	event.preventDefault();
	$(this).text('Please wait..');
	$.get(Wo_Ajax_Requests_File(), {f:'admin_setting', s: 'auto_group_like', users: $('#users').val()}, function(data, textStatus, xhr) {
		$('#users-btn').text('Saved!');
		setTimeout(function () {
			$('#users-btn').text('Save');
		}, 4000);
	});
});
</script>