<div class="container-fluid">
    <div>
        <h3>Manage Site Advertisements</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Advertisements</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Manage Site Advertisements</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Manage Site Advertisements</h6>
                    <div class="ads-settings-alert"></div>
                    <form class="ads-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Header <small>(Appears on all pages right under the nav bar)</small></label>
                                <textarea name="header" id="header" class="form-control" cols="30" rows="5"><?php echo Wo_GetAd('header', true);?></textarea>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Sidebar <small>(Appears on the bottom of home sidebar)</small></label>
                                <textarea name="sidebar" id="sidebar" class="form-control" cols="30" rows="5"><?php echo Wo_GetAd('sidebar', true);?></textarea>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Footer <small>(Appears on all pages right before the footer)</small></label>
                                <textarea name="footer" id="footer" class="form-control" cols="30" rows="5"><?php echo Wo_GetAd('footer', true);?></textarea>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Posts 1 <small>(Appears after 10 posts are loaded, between the posts)</small></label>
                                <textarea name="post_first" id="post_first" class="form-control" cols="30" rows="5"><?php echo Wo_GetAd('post_first', true);?></textarea>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Posts 2 <small>(Appears after 20 posts are loaded, between the posts)</small></label>
                                <textarea name="post_second" id="post_second" class="form-control" cols="30" rows="5"><?php echo Wo_GetAd('post_second', true);?></textarea>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Posts 3 <small>(Appears after 30 posts are loaded, between the posts)</small></label>
                                <textarea name="post_third" id="post_third" class="form-control" cols="30" rows="5"><?php echo Wo_GetAd('post_third', true);?></textarea>
                            </div>
                        </div>

                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>
$(function() {
    var form_ads_settings = $('form.ads-settings');
    form_ads_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_ads',
        beforeSend: function() {
            form_ads_settings.find('.waves-effect').text('Please wait..');
        },
        beforeSubmit : function(arr, $form, options){
            for (var i = 0; i < arr.length; i++) {
                if (arr[i].name == "header") {
                    arr[i].value = btoa(unescape(encodeURIComponent($('#header').val())));
                }
                if (arr[i].name == 'footer') {
                    arr[i].value = btoa(unescape(encodeURIComponent($('#footer').val())));
                }
                if (arr[i].name == 'watch_side_bar') {
                    arr[i].value = btoa(unescape(encodeURIComponent($('#watch_side_bar').val())));
                }
                if (arr[i].name == 'watch_comments') {
                    arr[i].value = btoa(unescape(encodeURIComponent($('#watch_comments').val())));
                }
            }
          // delete arr[0];
          // delete arr[1];
          // delete arr[2];
          // delete arr[3];
          // delete arr[4];
          // delete arr[5];
          // arr.push({name:'header', value:btoa(unescape(encodeURIComponent($('#header').val())))});
          // arr.push({name:'sidebar', value:btoa(unescape(encodeURIComponent($('#sidebar').val())))}); 
          // arr.push({name:'footer', value:btoa(unescape(encodeURIComponent($('#footer').val())))}); 
          // arr.push({name:'post_first', value:btoa(unescape(encodeURIComponent($('#post_first').val())))}); 
          // arr.push({name:'post_second', value:btoa(unescape(encodeURIComponent($('#post_second').val())))}); 
          // arr.push({name:'post_third', value:btoa(unescape(encodeURIComponent($('#post_third').val())))}); 
        },
        success: function(data) {
            if (data.status == 200) {
                form_ads_settings.find('.waves-effect').text('Save');
                $("html, body").animate({ scrollTop: 0 }, "slow");
                $('.ads-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Ads updated successfully</div>');
                setTimeout(function () {
                    $('.ads-settings-alert').empty();
                }, 2000);
            }
        }
    });
});
</script>